"""Adicionando campo is_admin na tabela usuarios

Revision ID: 57ee732001e0
Revises: 
Create Date: 2025-04-18 09:54:33.595948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ee732001e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PAGAMENTO')
    op.drop_table('USUARIO')
    op.drop_table('SERVICO')
    op.drop_table('AGENDAMENTO')
    op.drop_table('AGENDAMENTO_SERVICO')
    op.drop_table('PET')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PET',
    sa.Column('id_pet', sa.INTEGER(), nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), nullable=False),
    sa.Column('nome_pet', sa.VARCHAR(length=120), nullable=False),
    sa.Column('raca', sa.VARCHAR(length=120), nullable=True),
    sa.Column('idade', sa.INTEGER(), nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('peso', sa.FLOAT(), nullable=True),
    sa.Column('castrado', sa.BOOLEAN(), nullable=True),
    sa.Column('alimentacao', sa.TEXT(), nullable=True),
    sa.Column('saude', sa.TEXT(), nullable=True),
    sa.Column('foto_pet', sa.BLOB(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('data_cadastro', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIO.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pet')
    )
    op.create_table('AGENDAMENTO_SERVICO',
    sa.Column('id_agendamento', sa.INTEGER(), nullable=False),
    sa.Column('id_servico', sa.INTEGER(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=True),
    sa.Column('valor', sa.FLOAT(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['id_agendamento'], ['AGENDAMENTO.id_agendamento'], ),
    sa.ForeignKeyConstraint(['id_servico'], ['SERVICO.id_servico'], ),
    sa.PrimaryKeyConstraint('id_agendamento', 'id_servico')
    )
    op.create_table('AGENDAMENTO',
    sa.Column('id_agendamento', sa.INTEGER(), nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), nullable=False),
    sa.Column('id_pet', sa.INTEGER(), nullable=False),
    sa.Column('data_entrada', sa.DATETIME(), nullable=False),
    sa.Column('data_saida', sa.DATETIME(), nullable=False),
    sa.Column('observacoes', sa.TEXT(), nullable=True),
    sa.Column('valor_total', sa.FLOAT(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['id_pet'], ['PET.id_pet'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIO.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_agendamento')
    )
    op.create_table('SERVICO',
    sa.Column('id_servico', sa.INTEGER(), nullable=False),
    sa.Column('nome_servico', sa.VARCHAR(length=120), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('valor_hora', sa.FLOAT(), nullable=True),
    sa.Column('valor_dia', sa.FLOAT(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id_servico')
    )
    op.create_table('USUARIO',
    sa.Column('id_usuario', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('nome_user', sa.VARCHAR(length=120), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=14), nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=200), nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('foto_user', sa.BLOB(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('data_cadastro', sa.DATETIME(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('PAGAMENTO',
    sa.Column('id_pagamento', sa.INTEGER(), nullable=False),
    sa.Column('id_agendamento', sa.INTEGER(), nullable=False),
    sa.Column('data_pagamento', sa.DATETIME(), nullable=True),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('tipo_pagamento', sa.VARCHAR(length=50), nullable=True),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['id_agendamento'], ['AGENDAMENTO.id_agendamento'], ),
    sa.PrimaryKeyConstraint('id_pagamento')
    )
    # ### end Alembic commands ###
